<a href="https://colab.research.google.com/github/differntiation/Story/blob/master/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy->Numerical Python

Advantage of Numpy Arrays
1.   Allows several MAthematical operations
2.   faster opeartions



In [3]:
import numpy as np


List vs Numpy-Time Taken

In [2]:
from time import process_time

Time taken By List

In [4]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.001544237999999698


In [5]:
np_array=np.array([i for i in range(100000)])
start_time=process_time()
np_array+=5
end_time=process_time()
print(end_time-start_time)


0.0003822690000001572


Numpy Arrays:- There is no comma between element and nd array means n-dimensional array

In [6]:
#list
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [13]:
#1-d array
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)
np_array.shape   # it gives dimension of array(row,col)

[1 2 3 4 5]


(5,)

In [12]:
#Creating an 2-d array
b=np.array([(1,2,3),(4,5,6)])
print(b)
type(b)
b.shape     # it gives dimension of array(row,col)


[[1 2 3]
 [4 5 6]]


(2, 3)

In [14]:
#if element is floating point
c=np.array([(1,2,3),(3,4,5)],dtype=float)
print(c)

[[1. 2. 3.]
 [3. 4. 5.]]


Initial Placeholder in numpy arrays

In [15]:
#create numpy array of zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [16]:
#create numpy array of ones
y=np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [17]:
#array of particular value
z=np.full((5,4),5)  # here matrix dimension is (5,4) with element 5
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
#crete an identity matrix :- diagonal value is 1
a=np.eye(4)
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
#create numpy array with random value
n=np.random.random((3,4))   #here we random values between 0 and 1
print(n)

[[0.92782687 0.69856205 0.88449648 0.33440372]
 [0.70686073 0.13207733 0.84556384 0.24107553]
 [0.13619569 0.80431845 0.70958065 0.99384608]]


In [20]:
#random integer value array within specifixc range
c=np.random.randint(10,100,(3,5))  # HERE  dimension is (3,5) and element between 10 and 100
print(c)

[[81 23 77 53 68]
 [35 27 14 73 84]
 [52 80 98 17 12]]


In [22]:
#Array of eevenly spaced value
d=np.linspace(10,30,6) #here it print array which is from 10 to 30 and no of values is  5
print(d)

[10. 14. 18. 22. 26. 30.]


In [24]:
#array of evenly space value
e=np.arange(10,30,6)  #here it print array which is from 10 to 30 and eqully space of 6
print(e)


[10 16 22 28]


In [25]:
#convert list to numpy array
list2=[10,20,20,20,30]
np_array=np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 30]


numpy.ndarray

Analysing a Numpy Arry

In [26]:
c=np.random.randint(10,90,(5,5))
print(c)

[[11 54 78 74 83]
 [31 53 70 72 88]
 [85 44 73 15 87]
 [68 79 89 35 39]
 [73 50 48 49 33]]


In [27]:
#array dimension
print(c.shape)

(5, 5)


In [28]:
#number of dimension
print(c.ndim)  #here only 2 row and col

2


In [29]:
#number of element in an arry
print(c.size)

25


In [30]:
#checkin the datatype
print(c.dtype)

int64


MAthematical operation on numpy array

In [31]:
list1=[1,2,3,4,5]
list2=[1,2,3,4,5]
print(list1+list2)  #concatenate joins two

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [33]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(0,10,(3,3))
print(a)
print(b)

[[4 0 6]
 [1 9 5]
 [7 6 4]]
[[6 0 5]
 [1 1 7]
 [3 2 9]]


In [36]:
#here adding element wise and not concatenation happen
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[10  0 11]
 [ 2 10 12]
 [10  8 13]]
[[-2  0  1]
 [ 0  8 -2]
 [ 4  4 -5]]
[[24  0 30]
 [ 1  9 35]
 [21 12 36]]
[[0.66666667        nan 1.2       ]
 [1.         9.         0.71428571]
 [2.33333333 3.         0.44444444]]


<ipython-input-36-860f65d3f93e>:5: RuntimeWarning: invalid value encountered in divide
  print(a/b)


In [38]:
#other method to do the same
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[10  0 11]
 [ 2 10 12]
 [10  8 13]]
[[-2  0  1]
 [ 0  8 -2]
 [ 4  4 -5]]
[[24  0 30]
 [ 1  9 35]
 [21 12 36]]
[[0.66666667        nan 1.2       ]
 [1.         9.         0.71428571]
 [2.33333333 3.         0.44444444]]


<ipython-input-38-863c63bc6d1d>:4: RuntimeWarning: invalid value encountered in divide
  print(np.divide(a,b))


Array Manipulation

In [39]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[1 4 7]
 [1 8 1]]
(2, 3)


In [40]:
#Transpose trans
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[1 1]
 [4 8]
 [7 1]]
(3, 2)


In [41]:
#Method 2
trans2=array.T
print(trans2)
print(trans2.shape)

[[1 1]
 [4 8]
 [7 1]]
(3, 2)


In [44]:
#Reshaping a array
b=array.reshape(2,3)
print(b)
print(b.shape)

[[1 4 7]
 [1 8 1]]
(2, 3)
